### ISSUE TITLE
SuperResolution x2 instead of x4

### ISSUE THREAD

**Issue by Alexadar** [Stability-AI/stablediffusion#110]
Hi!
Is it possible to do x2 super resolution instead of x4 somehow, in order to save VRAM? Without resizing of an input image

**Comment by OrangeJuly56** [comment]
Currently, stable diffusion upscaler only has e an x4 model. But we are working on upscale. Please follow our update. Cheers!

**Comment by Alexadar** [comment]
Thanks!

Just for everyone else who is struggling: resize 512->256 and do x4 upscale (with xformers) do really work on 15GB VRAM however image quality is terrible because the information was lost during the initial resize
