### ISSUE TITLE
Does inpainting model support 768*768 or bigger images? 

### ISSUE THREAD

**Issue by FBehrad** [Stability-AI/stablediffusion#111]
When I use the inpainting model, available on hugging face, I get the following error with the input size of 768 by 768. However, everything works fine with 512 by 512 images.  Does inpainting model support 768*768 or bigger images? Can I use stable diffusion v2 inpainting model with arbitrary input size?
```
latent_model_input = torch.cat([latent_model_input, mask, masked_image_latents], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 96 for tensor number 2 in the list.
```

**Comment by FBehrad** [comment]
To whom it may concern,
I found two parameters called height and width control the size of the mask and the noise tensor. When we feed an image whose size is not 512x512 to the model, the default value of height and width (512) causes an error. By setting these two parameters manually, the inpainting model supports arbitrary input sizes. 
If you are using diffusers, you should predict the inpainted area using the following code:

```
img = Image.open(r"test.jpg").resize((768, 512))
msk = Image.open(r'mask.jpg').resize((768, 512))
.
.
.
images = pipe(prompt=[prompt] * batch, image=img, mask_image=msk, height=512, width=768
                          # ,num_inference_steps=steps, guidance_scale=guidance_scale
                          ).images
```

**Comment by BeastDD** [comment]
Hello,

I am new to this, I hope you won't mind me asking but where are the parameters for width and height that you found? as in what folder and file do I need to edit to add this code so that I can run 512 and 768 models at the same time in my installation?

Currently my installation is on 768 models so I can run 2.1 stability diffusion model just fine as well as any model on 768 format. However, every time I try to run something in 512 I get the "mismatch" error :(

Thank you!

**Comment by FBehrad** [comment]
Hello, 

These parameters (height and width) must be a multiple of 64. In this case, I have used (768, 512), but you can use any other sizes.  
I found this parameters in a file called "pipeline_stable_diffusion_inpaint.py". For me, this file is located in site-packages\diffusers\pipelines\stable_diffusion. In lines 633 and 634, height and width are defined.

**Comment by xiao2mo** [comment]
useful! mark
