### ISSUE TITLE
[Tutorial] Transform Your Selfie into a Stunning AI Avatar with Stable Diffusion - Better than Lensa for Free

### ISSUE THREAD

**Issue by FurkanGozukara** [Stability-AI/stablediffusion#114]
https://www.youtube.com/watch?v=mnCY8uM7E50

[![image](https://user-images.githubusercontent.com/19240467/208475654-9902392b-6140-4246-9ee0-40f513a905e4.png)](https://www.youtube.com/watch?v=mnCY8uM7E50)

In this video, I will show you how to create your own Lensa app-like magic avatars without using any third-party apps. Our method ensures 100% privacy, unlike uploading your personal photos to external apps and platforms. I am sure you have seen many people sharing their magic avatars on social media. While these paid apps use free open-source AI models, they still require payment. Additionally, AI image generation apps may keep your private photos and use them as they please. Instead of paying and trusting the goodwill of these paid apps, we will use these open-source public AI models ourselves. I will provide step-by-step instructions, so even those with no technical expertise can follow along. We will be using Google's Colab, a free #AI platform that offers access to a powerful GPU at no cost. Therefore, this tutorial can even be completed on a mobile phone without a PC. All you need is a Gmail account. Once we train the open-source image generation model #StableDiffusion with #DreamBooth by using our own portrait images, the possibilities are endless. Unlike other applications, the method I will demonstrate does not impose any limitations on image generation. You will be able to freely compose any kind of image as many times as you desire. You can not only generate your own avatars, but also any other images you want, such as highly detailed car images or landscapes.

**Comment by FurkanGozukara** [comment]
**you can add this tutorial to the guide - readme section of the repository**

**Comment by kopiro** [comment]
Is it possible to achieve the same using DiffusionBee on your local Mac?

**Comment by FurkanGozukara** [comment]
> Is it possible to achieve the same using DiffusionBee on your local Mac?

I don't know mac but you can do on windows
