### ISSUE TITLE
Is my result what is expected? Not sure if SD is working to "specifications"

### ISSUE THREAD

**Issue by vmajor** [Stability-AI/stablediffusion#123]
Running the default txt2img "a professional photograph of an astronaut riding a horse" gives me this output:
![grid-0001](https://user-images.githubusercontent.com/5185905/209783496-bd96d299-b2f4-44ef-8de5-39229d1d29bc.png)

It is interesting, but does not resemble any astronaut containing sample image, nor a "professional photo" so I am not sure if something is broken with my installation. It was not that simple to make it work in Windows 10.

**Comment by valo** [comment]
Check if the width and height you generate the images is the same as the resolution of the model. SD 1.5 is 512x512. SD 2.0 has a 768x768 version
