### ISSUE TITLE
COLLAB LINK for base model inference

### ISSUE THREAD

**Issue by AlexWortega** [Stability-AI/stablediffusion#16]
https://colab.research.google.com/drive/1cuzz-TcAXsqlCPqqa8U7LltMmeZuBYkh?usp=sharing

**Comment by 0xdevalias** [comment]
Semi-related:

- https://github.com/Stability-AI/stablediffusion/issues/9

**Comment by backnotprop** [comment]
Here is a link for base depth img2img inference:

https://github.com/backnotprop/Colab-Stable-Diffusion-2-Depth-UI

**Comment by woctezuma** [comment]
Alternatively, run [`stable_diffusion.ipynb`][colab-notebook-stable-diffusion]. [![Open In Colab][colab-badge]][colab-notebook-stable-diffusion]

[colab-notebook-stable-diffusion]: <https://colab.research.google.com/github/woctezuma/stable-diffusion-colab/blob/main/stable_diffusion.ipynb>
[colab-badge]: <https://colab.research.google.com/assets/colab-badge.svg>
