### ISSUE TITLE
Can I run this project on Mac OS with m1

### ISSUE THREAD

**Issue by zoozooll** [Stability-AI/stablediffusion#171]
Hey everyone! I have get a apple mac studio with m1 max chip. Can I run this project on my mac studio? I found cuda is disable to run on mac os with m1.

**Comment by Tps-F** [comment]
Yes!
My fork can
https://github.com/Tps-F/stablediffusion

**Comment by enzyme69** [comment]
You sure can! Mac Studio M1 Max chip should be sufficient. Especially if you have 32 GB or more RAM on the GPU. 

Test it with DrawThingsAI app or Diffusion Bee, or if you feel challenged go inside Terminal, install Automatic1111 WebUI for Stable Diffusion.

Ask me more if you have question. I am Blender Sushi Guy.

**Comment by Tps-F** [comment]
> Yes!
> My fork can
> https://github.com/Tps-F/stablediffusion
> 

More information 
https://github.com/Stability-AI/stablediffusion/pull/163

**Comment by dpankros** [comment]
Apple also has a version: https://github.com/apple/ml-stable-diffusion
My experience is that it doesn't give the same results as this library, but I may have done something wrong in the process of configuring things.
