### ISSUE TITLE
loading v2-1_768-ema-pruned.ckpt

### ISSUE THREAD

**Issue by nickums** [Stability-AI/stablediffusion#188]
Into what directory should I download this file?
(In have to download from my browser, the download from the python script is always  forcibly closed after only a few %)

**Comment by dpankros** [comment]
You can put it anywhere you want and then reference it in a script option e.g. `python scripts/txt2img.py --ckpt "/<mydir>/v2-1_768-ema-pruned.ckpt"...`

Personally, I create a `ckpts` directory and reference them from there, but that's just my preference.

**Comment by nickums** [comment]
Thankyou!
