### ISSUE TITLE
t2i result

### ISSUE THREAD

**Issue by sunmeng7** [Stability-AI/stablediffusion#211]
I use the base weight and run 'a professional photograph of an astronaut riding a horse', the result looks not good.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/50901976/227197844-d69294a9-ac2c-4033-84f0-084f15160cc3.png">
How to solve it?

**Comment by Irennnne** [comment]
Hi, my generated images look like yours through v2-inference. How did you solve this problem? Thank you!

**Comment by sunmeng7** [comment]
@Irennnne Maybe the height and weight are not correct in the resolution, I can't remember, sorry.
