### ISSUE TITLE
ModuleNotFoundError: No module named 'ldm.models.diffusion.dpm_solver'

### ISSUE THREAD

**Issue by universewill** [Stability-AI/stablediffusion#24]
cannot find dpm_solver module

**Comment by fuomag9** [comment]
@universewill How did you solve it? I can import via cli the module just fine but not inside the script...

**Comment by conrman** [comment]
@fuomag9 I solved by adding the repo's directory to the `PYTHONPATH`: 

```
cd path/to/stablediffusion
export PYTHONPATH=$PYTHONPATH:.
```

**Comment by JingfengYao** [comment]
> It works. Thanks a lot.

**Comment by universewill** [comment]
> @universewill How did you solve it? I can import via cli the module just fine but not inside the script...

Add __init__.py to the module folders

**Comment by zhaoyuzhi** [comment]
Thanks [conrman](https://github.com/conrman), it works.

```bash
cd path/to/stablediffusion
export PYTHONPATH=$PYTHONPATH:.
```
