### ISSUE TITLE
ModuleNotFoundError: No module named 'omegaconf' (Please provide full installation instructions)

### ISSUE THREAD

**Issue by n00mkrad** [Stability-AI/stablediffusion#25]
I tried to install it like this:

* New conda environment with python 3.9
* `conda install pytorch==1.12.1 torchvision==0.13.1 -c pytorch`
* `pip install transformers==4.19.2 diffusers invisible-watermark`
* `pip install -e .`
* Trying to run the script, I get `ModuleNotFoundError: No module named 'omegaconf'`

**Comment by n00mkrad** [comment]
Forgot to run `pip install -r requirements.txt`.

This should probably be added to the readme.

**Comment by jcRisch** [comment]
Official READ.ME is suggesting to create conda env from Latent Diffision Github (https://github.com/CompVis/latent-diffusion) and to update it with:
```
conda install pytorch==1.12.1 torchvision==0.13.1 -c pytorch
pip install transformers==4.19.2 diffusers invisible-watermark
pip install -e .
```

But it implies lib errors.

READM.ME should suggest to do:
```
conda env create -f environment.yaml
conda activate ldm
pip install -r requirements.txt
```

**Comment by jcRisch** [comment]
I wrote an article with instructions I followed to make it work: 
https://medium.com/@jcrsch/stablediffusion-2-make-it-work-on-your-linux-1e30716eeee4
