### ISSUE TITLE
Model distillation details

### ISSUE THREAD

**Issue by nicolas-dufour** [Stability-AI/stablediffusion#27]
You mention that the model has been distilled following https://arxiv.org/abs/2202.00512.
Can you give more details on that? What's the targeted number of steps? Does it goes as far as 4 steps distilled models like in the paper?
Has it been tuned distilled for guided diffusion models like in https://arxiv.org/abs/2210.03142?

Thanks!

**Comment by mkaic** [comment]
Unless I missed something, I don't think they actually distilled this model, they merely adopted a configuration from the distillation paper— V-Prediction. I have been poking around at the possibility of distilling the model myself recently according to that second paper you linked, "On Distillation of Guided Diffusion Models", but I've been struggling to figure out how to implement it.

**Comment by nicolas-dufour** [comment]
Hum ok thanks! That's too bad, it might have been a great improvement to have a SD distilled model!
