### ISSUE TITLE
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]). By using latest open-clip-torch

### ISSUE THREAD

**Issue by jacob-kang** [Stability-AI/stablediffusion#402]
> RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (3, 3).

This error is occred if I use the latest version of open-clip-torch.
But, after I use pip install open-clip-torch==2.24.0, it's solved.

I need to use latest version open-clip-torch to combine other module to this stable diffusion. but the other module has depandacy of using latest version.

Any reason why it is happened about attn_mask?

thanks

**Comment by amanikiruga** [comment]
this is happening to me too!
