### ISSUE TITLE
when will  Image Upscaling with Stable Diffusion function be available?

### ISSUE THREAD

**Issue by mule-engineer13** [Stability-AI/stablediffusion#42]
Hi Stability-AI team😀

I have a question.
I would appreciate it if you could answer.

I want to use the Image Upscaling with Stable Diffusion function.
However, when I checked the link below, it still didn't seem to work.
https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler

It said "Use it with diffusers (coming soon)".

when will it be available?
And if there are any other demo pages that can use the upscaling function, please let me know.

Thank you.

**Comment by ThibaultLSDC** [comment]
Hey this link worked for me:
[https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler/resolve/main/x4-upscaler-ema.ckpt](url)

**Comment by mule-engineer13** [comment]
Thank you for answering.

When I tried it on Google Colab, I got the following error.

●code-------------------------------
!python scripts/gradio/inpainting.py scripts/gradio/superresolution.py configs/stable-diffusion/x4-upscaling.yaml x4-upscaler-ema.ckpt
---------------------------------------

●error--------------------------------
Traceback (most recent call last):
  File "scripts/gradio/inpainting.py", line 160, in <module>
    sampler = initialize_model(sys.argv[1], sys.argv[2])
  File "scripts/gradio/inpainting.py", line 28, in initialize_model
    config = OmegaConf.load(config)
  File "/usr/local/lib/python3.7/dist-packages/omegaconf/omegaconf.py", line 184, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "/usr/local/lib/python3.7/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.7/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.7/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.7/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.7/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python3.7/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.7/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.7/dist-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/content/drive/MyDrive/stablediffusion-main/scripts/gradio/superresolution.py", line 20, column 35
------------------------------------------------

Can you guess the cause?
And,If you have a GoogleColab demo, could you share it?

**Comment by ThibaultLSDC** [comment]
Hi, sorry I deleted my answer 'cause the link didn't work in github for some reason. (?) The model checkpoints are download-able in the Hugginface model card.
Anyways your error is because you're calling both scripts/gradio/inpainting.py and scripts/gradio/superresolution.py. You should run:
`!python scripts/gradio/superresolution.py configs/stable-diffusion/x4-upscaling.yaml x4-upscaler-ema.ckpt`
for upscaling.
I ran into the same issue and I guess there might have been a mistake in the README yesterday ?
Hope this helps

**Comment by mule-engineer13** [comment]
Thank you for answering！
I'll try！

**Comment by lucellent** [comment]
> Hi, sorry I deleted my answer 'cause the link didn't work in github for some reason. (?) The model checkpoints are download-able in the Hugginface model card. Anyways your error is because you're calling both scripts/gradio/inpainting.py and scripts/gradio/superresolution.py. You should run: `!python scripts/gradio/superresolution.py configs/stable-diffusion/x4-upscaling.yaml x4-upscaler-ema.ckpt` for upscaling. I ran into the same issue and I guess there might have been a mistake in the README yesterday ? Hope this helps

Is it possible to use the upscaler on our own images, and not have to first generate SD images?

**Comment by mule-engineer13** [comment]
Thank you for answering.
II want to upscale a local image. Is upscaling possible even if the image is not generated by SD?

**Comment by mule-engineer13** [comment]
Using the code you gave me below, I was able to start inference.
`!python scripts/gradio/superresolution.py configs/stable-diffusion/x4-upscaling.yaml x4-upscaler-ema.ckpt`

However, even after 30 minutes or more, it does not proceed from the following display.

●log
```
No module 'xformers'. Proceeding without it.
LatentUpscaleDiffusion: Running in v-prediction mode
DiffusionWrapper has 473.40 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 64, 64) = 16384 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: 100% 3.94G/3.94G [01:11<00:00, 55.5MB/s]
/usr/local/lib/python3.7/dist-packages/gradio/deprecation.py:44: UserWarning: You have unused kwarg parameters in Number, please remove them: {'min': 0.0, 'max': 1.0}
  f"You have unused kwarg parameters in {cls}, please remove them: {kwargs}"
/usr/local/lib/python3.7/dist-packages/gradio/deprecation.py:44: UserWarning: You have unused kwarg parameters in Number, please remove them: {'min': 0, 'max': 350, 'step': 1}
  f"You have unused kwarg parameters in {cls}, please remove them: {kwargs}"
Running on local URL:  http://127.0.0.1:7860/

To create a public link, set `share=True` in `launch()`.
```


●Environment
googlecolab free version gpu


●pytorch virsion
```
open-clip-torch               2.7.0
pytorch-lightning             1.4.2
torch                         1.10.0
torchaudio                    0.10.0
torchmetrics                  0.6.0
torchsummary                  1.5.1
torchtext                     0.11.0
torchvision                   0.10.1
```


Does it take this long?
If you know any improvement measures, could you tell me?

**Comment by mule-engineer13** [comment]
●gpu version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

**Comment by kongfanyu06** [comment]
> Using the code you gave me below, I was able to start inference. `!python scripts/gradio/superresolution.py configs/stable-diffusion/x4-upscaling.yaml x4-upscaler-ema.ckpt`
> 
> However, even after 30 minutes or more, it does not proceed from the following display.
> 
> ●log
> 
> ```
> No module 'xformers'. Proceeding without it.
> LatentUpscaleDiffusion: Running in v-prediction mode
> DiffusionWrapper has 473.40 M params.
> making attention of type 'vanilla' with 512 in_channels
> Working with z of shape (1, 4, 64, 64) = 16384 dimensions.
> making attention of type 'vanilla' with 512 in_channels
> Downloading: 100% 3.94G/3.94G [01:11<00:00, 55.5MB/s]
> /usr/local/lib/python3.7/dist-packages/gradio/deprecation.py:44: UserWarning: You have unused kwarg parameters in Number, please remove them: {'min': 0.0, 'max': 1.0}
>   f"You have unused kwarg parameters in {cls}, please remove them: {kwargs}"
> /usr/local/lib/python3.7/dist-packages/gradio/deprecation.py:44: UserWarning: You have unused kwarg parameters in Number, please remove them: {'min': 0, 'max': 350, 'step': 1}
>   f"You have unused kwarg parameters in {cls}, please remove them: {kwargs}"
> Running on local URL:  http://127.0.0.1:7860/
> 
> To create a public link, set `share=True` in `launch()`.
> ```
> 
> ●gpu version(googlecolab free version gpu)
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2021 NVIDIA Corporation
> Built on Sun_Feb_14_21:12:58_PST_2021
> Cuda compilation tools, release 11.2, V11.2.152
> Build cuda_11.2.r11.2/compiler.29618528_0
> ```
> 
> ●pytorch version
> 
> ```
> open-clip-torch               2.7.0
> pytorch-lightning             1.4.2
> torch                         1.10.0
> torchaudio                    0.10.0
> torchmetrics                  0.6.0
> torchsummary                  1.5.1
> torchtext                     0.11.0
> torchvision                   0.10.1
> ```
> 
> Does it take this long? If you know any improvement measures, could you tell me?
Open this url: http://127.0.0.1:7860/ on your browser, then choose a image to run.

**Comment by masahiroview** [comment]
I have an additional question.
I tried the demo below. Is this stable-diffusion 2.0?
https://huggingface.co/spaces/stabilityai/stable-diffusion-upscaler

**Comment by mule-engineer13** [comment]
Access is denied when opening http://127.0.0.1:7860/.
A screen with ERR_CONNECTION_REFUSED is displayed.

**Comment by mule-engineer13** [comment]
I have an additional question.
I tried the demo below. Is this stable-diffusion 2.0?
https://huggingface.co/spaces/stabilityai/stable-diffusion-upscaler

**Comment by mule-engineer13** [comment]
> Access is denied when opening http://127.0.0.1:7860/.
> A screen with ERR_CONNECTION_REFUSED is displayed.


I was able to get this to work using a public URL.
Thank you.

**Comment by Qingcsai** [comment]
@mule-engineer13 Hi, how did you get the http://127.0.0.1:7860/ work using a public URL, I also show this but my access is denied when opending it.
