### ISSUE TITLE
Question: Why so many stable diffusions?

### ISSUE THREAD

**Issue by Explosion-Scratch** [Stability-AI/stablediffusion#47]
I've seen numerous Stable Diffusions around GitHub, many with significant amounts of stars as well, can someone explain what the difference is between these, and the pros and cons of each?

- https://github.com/Stability-AI/StableDiffusion
- https://github.com/runwayml/stable-diffusion
- https://github.com/compvis/stable-diffusion

**Comment by woctezuma** [comment]
Different fine-tuning. The order in your post is v2.0, v1.5 and v1.4.

**Comment by G-force78** [comment]
Was about to ask this on hugging face, there are FIVE new sd 2.0 models, I was curious in particular why inpaint and depth weren't  the same model? Also why 768 doesn't have depth2img? 
Correct me if I'm wrong but I think 2.0inpaint is just a modified and neutered version of 1.5inpaint that runwayML released.

**Comment by woctezuma** [comment]
In case of doubts, stick to the official releases by CompVis, RunwayML and StabilityAI.

**Comment by Explosion-Scratch** [comment]
Thanks guys! Appreciate it!
