### ISSUE TITLE
[Feature Request]: img2txt - Image to text ? 

### ISSUE THREAD

**Issue by gabrielsubtil** [Stability-AI/stablediffusion#48]
with current technology would it be possible to **ask the AI to generate a text from an image**? in order to know what technology could describe the image, a tool for AI to describe the image for us.

(com a tecnologia atual seria possivel solicitar a IA gerar um texto a partir de uma imagem ? com a finalidade de saber o que a tecnologia poderia descrever da imagem, uma ferramenta para a IA descrever a imagem para a gente. )

**Comment by brycedrennan** [comment]
This does what you want. https://github.com/salesforce/BLIP

**Comment by gabrielsubtil** [comment]
> This does what you want. https://github.com/salesforce/BLIP

Thank you, that's exactly it! it works perfectly. I believe this feature should be highlighted in the main menu to make it "more intuitive" to use!

Thanks!
