### ISSUE TITLE
Watermark bias

### ISSUE THREAD

**Issue by maciej-zuk** [Stability-AI/stablediffusion#50]
I don't know if this is a good place to report such problems, but it seems that the network is overtrained on images containing watermarks. I'm posting an example of where it imprinted clearly recognizable dreamstime.com watermark.
![tmp80smcll8](https://user-images.githubusercontent.com/4552200/204058737-28940d77-2b0c-4834-9bd8-6ec74a489b54.png)

**Comment by gonferzika** [comment]
I get some images with watermarks here too, and i just begin to play with the new model, the previous V1 almost never generate watermarks for me.

**Comment by yunnieXx** [comment]
Pretty sure you can use a negative tag to remove most watermarks (watermark:-1)
