### ISSUE TITLE
Fine tuning the model

### ISSUE THREAD

**Issue by marctabog** [Stability-AI/stablediffusion#54]
Hello! First, thanks a lot for all your work !
Quick question, I tried to fine-tune the v2.0 of the model on new images using the same scripts I was using for the v1.4 v1.5 (dreambooth and textual inversion), but the results are very bad (almost only noise). 
1/ Is it normal ? (what is different about the model architecture / training that makes the training scripts not working well with v2.0?
2/ What should I look into to adapt the fine tuning scripts to work with v2.0 ?

Thanks a lot for your answers!

**Comment by OrangeJuly56** [comment]
Yeah trying 768x768 will work I think. V2.0 is better for fine-tuning afaIk!
