### ISSUE TITLE
no such file or directory: /usr/src/app/.cache/huggingface/hub/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K/refs/main

### ISSUE THREAD

**Issue by abcsimple** [Stability-AI/stablediffusion#73]
I download open_clip_pytorch_model.bin from huggingface and saved it in ./laion/CLIP-ViT-H-14-laion2B-s32B-b79K, but got the erro: no such file or directory: /usr/src/app/.cache/huggingface/hub/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K/refs/main.

I found that in file factory.py of open_clip lib, the model is required to download in line 156, without checking the model exists locally or not. Anyone can help me?

**Comment by Bowei-Li** [comment]
I got the same issue. Have you solved it?

**Comment by nielsrolf** [comment]
I just had a similar error that was resolved by upgrading openclip

**Comment by abcsimple** [comment]
> I just had a similar error that was resolved by upgrading openclip

what's the version of openclip in your env? mine is 2.7.0

**Comment by WellTung666** [comment]
I got the same issue.

**Comment by WellTung666** [comment]
I have solved this problem!
I installed 'open_clip_torch' on a computer with normal network, and then ran the following code:

```
import open_clip
open_clip.list_pretrained()
model, _, preprocess = open_clip.create_model_and_transforms('ViT-H-14', pretrained='laion2b_s32b_b79k')
model.eval()
context_length = model.context_length
vocab_size = model.vocab_size

print("Model parameters:", f"{np.sum([int(np.prod(p.shape)) for p in model.parameters()]):,}")
print("Context length:", context_length)
print("Vocab size:", vocab_size)
```
and then it will automatic download files in /.cache/huggingface/hub/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K/
Copy files to the same path on another computer, solve the problem!!!

**Comment by WellTung666** [comment]
> I got the same issue. Have you solved it?

you can try my way.
https://github.com/Stability-AI/stablediffusion/issues/73#issuecomment-1343820268
