### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'm'.

### ISSUE THREAD

**Issue by mandgie** [Stability-AI/stablediffusion#79]
Hi!

I'm using pyenv with python 3.9.5, when running:
`python scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt <model/768-v-ema.ckpt> --config configs/stable-diffusion/v2-inference-v.yaml --H 768 --W 768`
I receive the error` '_pickle.UnpicklingError: invalid load key, 'm'.'`

`python scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt <model/768-v-ema.ckpt> --config configs/stable-diffusion/v2-inference-v.yaml --H 768 --W 768
Global seed set to 42
Traceback (most recent call last):
  File "/Users/magnusfriberg/repos_private/stablediffusion/scripts/txt2img.py", line 289, in <module>
    main(opt)
  File "/Users/magnusfriberg/repos_private/stablediffusion/scripts/txt2img.py", line 190, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "/Users/magnusfriberg/repos_private/stablediffusion/scripts/txt2img.py", line 30, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "/Users/magnusfriberg/repos_private/stablediffusion/env/lib/python3.9/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/magnusfriberg/repos_private/stablediffusion/env/lib/python3.9/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'm'.`

**Comment by williamjamir** [comment]
Did you download the ckpt from hugginface with a logged user?
https://github.com/CompVis/stable-diffusion/issues/432#issuecomment-1295026109

**Comment by mandgie** [comment]
Yes, I had a look at that issue, however they receive an invalid load of key 'A', while I get 'm'?

**Comment by williamjamir** [comment]
Yeap, I was receiving with "<" or something like that.
My main take here is just to try to download the ckpt file properly with a logged user and accepting the terms and see if it solves the issue (at least for me it solved).

**Comment by mandgie** [comment]
I managed to resolve the issue.

**Comment by DongCoder7** [comment]
> 

how do u fix the problem? I just suffered the same issue

**Comment by Weigaa** [comment]
@williamjamir @mandgie @DongCoder7 May I ask if the problem has been solved? I had the same problem and logged into my account and re-downloaded ckpt, but still have the problem.

**Comment by Weigaa** [comment]
The reason is the path to ckpt with "<>", This mistake was so stupid that it made me misunderstand the readme.
