### ISSUE TITLE
ModuleNotFoundError: No module named 'torchtext.legacy'

### ISSUE THREAD

**Issue by chbfiv** [Stability-AI/stablediffusion#8]
Walked through the README and got this. I didn't use conda though to install pytorch might try to do that instead

```python
!python scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt models/ldm/768-v-ema.ckpt --config configs/stable-diffusion/v2-inference-v.yaml --H 768 --W 768 
```

```
Traceback (most recent call last):
  File "scripts/txt2img.py", line 11, in <module>
    from pytorch_lightning import seed_everything
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py", line 31, in <module>
    from torchtext.legacy.data import Batch
ModuleNotFoundError: No module named 'torchtext.legacy'
```

https://colab.research.google.com/drive/10jKS9pAB2bdN3SHekZzoKzm4jo2F4W1Q?usp=sharing

**Comment by FrancescoSaverioZuppichini** [comment]
same

**Comment by woctezuma** [comment]
Ditto after running the following on Google Colab:

```bash
%cd /content
!git clone https://github.com/Stability-AI/stablediffusion.git
%cd /content/stablediffusion
%pip install -q -r requirements.txt

!wget https://huggingface.co/stabilityai/stable-diffusion-2-base/resolve/main/512-base-ema.ckpt

!python scripts/txt2img.py \
 --config configs/stable-diffusion/v2-inference.yaml \
 --ckpt 512-base-ema.ckpt \
 --prompt "a professional photograph of an astronaut riding a horse" 
```

**Comment by woctezuma** [comment]
If you run:
```
%pip install -q torchtext==0.9
```
then you get a different error:
```
/usr/local/lib/python3.7/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "scripts/txt2img.py", line 10, in <module>
    from torchvision.utils import make_grid
  File "/usr/local/lib/python3.7/dist-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/__init__.py", line 18, in <module>
    from . import quantization
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/quantization/mobilenetv2.py", line 6, in <module>
    from torch.ao.quantization import QuantStub, DeQuantStub
ModuleNotFoundError: No module named 'torch.ao'
```

**Comment by 0xdevalias** [comment]
Googling the error message `No module named 'torchtext.legacy'`:

https://www.datasciencelearner.com/modulenotfounderror-no-module-named-torchtext-legacy-solved/

> The above Incorrect imports work properly in the lower version of [torchtext (0.10.0 or lower )](https://pypi.org/project/torchtext/0.10.0/). Because these versions have the same directory structure. We will use the pip package manager to downgrade torchtext module.  Here is the command for that-
> 
> `pip install torchtext==0.10.0`

Potentially related:

- https://github.com/pytorch/text/pull/1437
  - seemingly first released in [v0.12.0-rc1](https://github.com/pytorch/text/releases/tag/v0.12.0-rc1)

---

> If you run:
> 
> ```
> %pip install -q torchtext==0.10
> ```
> 
> then you get a different error:
> 
> ```
> ModuleNotFoundError: No module named 'torch.ao.quantization'
> ```

Potentially related/helpful:

- https://github.com/facebookresearch/d2go/issues/128
- https://github.com/facebookresearch/d2go/issues/141
- https://discuss.pytorch.org/t/cannot-import-name-quantstub-from-torch-ao-quantization/158979
- https://forums.fast.ai/t/cannot-import-name-quantstub-from-torch-ao-quantization/94078/3

---

Here are the relevant releases between those versions:

- https://github.com/pytorch/text/releases/tag/v0.11.2
- https://github.com/pytorch/text/releases/tag/v0.11.1
- https://github.com/pytorch/text/releases/tag/v0.11.0-rc3
- https://github.com/pytorch/text/releases/tag/v0.10.1
  - > This release depends on pytorch 1.9.1
- https://github.com/pytorch/text/releases/tag/v0.10.0

**Comment by 0xdevalias** [comment]
https://github.com/pytorch/text#installation

> The following are the corresponding `torchtext` versions and supported Python versions.

> PyTorch version | torchtext version | Supported Python version
> -- | -- | --
> nightly build | main | >=3.7, <=3.10
> 1.13.0 | 0.14.0 | >=3.7, <=3.10
> 1.12.0 | 0.13.0 | >=3.7, <=3.10
> 1.11.0 | 0.12.0 | >=3.6, <=3.9
> 1.10.0 | 0.11.0 | >=3.6, <=3.9
> 1.9.1 | 0.10.1 | >=3.6, <=3.9
> 1.9 | 0.10 | >=3.6, <=3.9
> 1.8.1 | 0.9.1 | >=3.6, <=3.9
> 1.8 | 0.9 | >=3.6, <=3.9
> 1.7.1 | 0.8.1 | >=3.6, <=3.9
> 1.7 | 0.8 | >=3.6, <=3.8
> 1.6 | 0.7 | >=3.6, <=3.8
> 1.5 | 0.6 | >=3.5, <=3.8
> 1.4 | 0.5 | 2.7, >=3.5, <=3.8
> 0.4 and below | 0.2.3 | 2.7, >=3.5, <=3.8

---

Based on that, it looks like you want to be using one of these combinations presumably?

> PyTorch version | torchtext version | Supported Python version
> -- | -- | --
> 1.10.0 | 0.11.0 | >=3.6, <=3.9
> 1.9.1 | 0.10.1 | >=3.6, <=3.9

**Comment by 0xdevalias** [comment]
- https://github.com/pytorch/pytorch/tree/v1.9.1/torch/ao/quantization
  - > The `pytorch/pytorch` repository doesn't contain the `torch/ao/quantization` path in `v1.9.1`
- https://github.com/pytorch/pytorch/tree/v1.10.2/torch/ao/quantization
  - Path seems to exist

**Comment by FrancescoSaverioZuppichini** [comment]
Guys how do you test and release software, what's your devops? It looks like there wasn't any test before making the announcement, I'd love to help for the future

**Comment by backnotprop** [comment]
The issue isnt torchtext, it's your version of pytorch_lighting, here's the most recent version that should work:

`!pip install pytorch-lightning==1.8.3.post0`

**Comment by woctezuma** [comment]
Yes, #30 (for newer versions of `pytorch-lightning` and `torchmetrics`) and #10 (for `invisible-watermark`) make the code run on Colab. However, there is a memory overflow on Colab, it seems. 😰  Maybe xformers are required.

**Comment by backnotprop** [comment]
@woctezuma try high runtime type if you have it:

In Colab : Runtime-> Change runtime type -> Runtime shape -> High-RAM

also for xformers there are precompiled versions you can grab if you dont want to wait:
https://github.com/TheLastBen/fast-stable-diffusion/tree/main/precompiled

**Comment by woctezuma** [comment]
Thanks! I will look into these options!

**Comment by woctezuma** [comment]
I don't think it is possible to run this script on the free version of Google Colab. Thanks for the help though.

For reference, this is what my Google Colab code looked like:

```
%cd /content
!git clone https://github.com/Stability-AI/stablediffusion.git
%cd /content/stablediffusion

!curl https://raw.githubusercontent.com/backnotprop/stablediffusion/backnotprop-patch-pytorch_lighting/requirements.txt -O
%pip install -q -r requirements.txt

%pip install -q invisible-watermark

!nvidia-smi
%pip install https://github.com/TheLastBen/fast-stable-diffusion/raw/main/precompiled/T4/xformers-0.0.13.dev0-py3-none-any.whl

!wget https://huggingface.co/stabilityai/stable-diffusion-2-base/resolve/main/512-base-ema.ckpt

!python scripts/txt2img.py \
 --config configs/stable-diffusion/v2-inference.yaml \
 --ckpt 512-base-ema.ckpt \
 --n_samples 1 --H 256 --W 256 \
 --prompt "a professional photograph of an astronaut riding a horse" 
```

**Comment by 0xdevalias** [comment]
> I don't think it is possible to run this script on the free version of Google Colab

Why not?

**Comment by 0xdevalias** [comment]
> > In Colab : Runtime-> Change runtime type -> Runtime shape -> High-RAM
>
> I don't see this in the free version of Google Colab.

For reference:
![image](https://user-images.githubusercontent.com/753891/203927342-eeb54fc4-ec14-4c6d-9589-63fe6c24244d.png)
![image](https://user-images.githubusercontent.com/753891/203927401-92d9cac5-2350-4621-8447-d2a578f30874.png)

**Comment by chbfiv** [comment]
Thanks! this resolved it with the additional collab recommendations above

```python
!pip install pytorch-lightning==1.8.3.post0
```

**Comment by thusinh1969** [comment]
> Guys how do you test and release software? What's your DevOps? It looks like there wasn't any test before making the announcement. I know people in DS world avoid SE best practices. Let me know if you need help for the future for testing and giving to the community the correct instruction to really make ML more open.

Same, I found this Facebook package is hilariously terribly released ! Facebook should NEVER release such product to public even for a test likes this. Sorry being very **upset** about this
