### ISSUE TITLE
Negative prompt?

### ISSUE THREAD

**Issue by tonydavis629** [Stability-AI/stablediffusion#94]
How do we input negative prompts when using the scripts?

**Comment by jamesthesnake** [comment]
I think that's just a parameter?

**Comment by tonydavis629** [comment]
It is not. There is only the option for prompt. The negative conditioning in the scripts are filled in with an empty string, telling me that maybe negative prompts are not meant to be used?

**Comment by jamesthesnake** [comment]
https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler it is here I'll go through the code

**Comment by mattmdjaga** [comment]
The examples here https://stability.ai/blog/stablediffusion2-1-release7-dec-2022, the post about 2.1 ,seem to imply negative prompts are added at the end of the prompt with a ": -2" to specify those prompts being negative. An example that they show is "a portrait of a beautiful blonde woman, fine - art photography, soft portrait shot 8 k, mid length, ultrarealistic uhd faces, unsplash, kodak ultra max 800, 85 mm, intricate, casual pose, centered symmetrical composition, stunning photos, masterpiece, grainy, centered composition : 2 | blender, cropped, lowres, poorly drawn face, out of frame, poorly drawn hands, blurry, bad art, blurred, text, watermark, disfigured, deformed, closed eyes : -2 ". When i tested this on the 2.1 checkpoint I had good results. This is just a guess tho.
