### ISSUE TITLE
__init__() got an unexpected keyword argument 'use_linear_in_transformer'

### ISSUE THREAD

**Issue by aniki-ly** [Stability-AI/stablediffusion#99]
I have installed stable-diffusion v2 and run following commands:
python scripts/img2img.py --prompt "A fantasy landscape, trending on artstation" --init-img test.jpeg --strength 0.8 --ckpt 768-v-ema.ckpt

but i got a error:
TypeError: __init__() got an unexpected keyword argument 'use_linear_in_transformer'

How to solve it?

**Comment by krrishdholakia** [comment]
You can try updating the version of stable-diffusion to the latest version, as this issue may have been addressed in a newer version. You can also try specifying the use_linear_in_transformer argument when calling init().

Let me know if that helps!

Got this from Clerkie (ai code debugger bot) - https://bit.ly/3EFAV8A

<img width="1525" alt="Screen Shot 2022-12-13 at 10 38 39 AM" src="https://user-images.githubusercontent.com/17561003/207231650-538523ae-bb37-4055-96d2-4edbdf02d460.png">
